<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <Compile Include="../../srcCs/Infrastructure/CliParser.cs" Link="Infrastructure/CliParser.cs" />
    <Compile Include="../../srcCs/Infrastructure/Parameters.cs" Link="Infrastructure/Parameters.cs" />
    <None Include="../../resource/scripts/cs_execution_scripts/perftest_cs.bat"
          Link="perftest_cs.bat"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
